version: 0.1

phases:
  install:
    commands:
      - npm install

  pre_build:
    commands:
      - echo installing dependencies...
      - npm install

  build:
    commands:
      - echo building...
      - npm run dev


artifacts:
  files:
    - package.json
    - package-lock.json
    - "build/**/*"
  discard-paths: no
  base-directory: build