version: 0.1

phases:
  install:
    commands:
      - echo installing nodejs...
      - curl -fsSL https://deb.nodesource.com/setup_20.x | bash - &&\
      - sudo apt-get install -y nodejs
      - sudo apt-get install gcc g++ make
      -  curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/yarnkey.gpg >/dev/null
      - echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      - sudo apt-get update && sudo apt-get install yarn

  pre_build:
    commands:
      - echo installing dependencies...
      - npm install

  build:
    commands:
      - echo building...
      - npm run dev


artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build