version: 0.1

phases:
  install:
    commands:
      - echo installing nodejs...
      - curl -fsSL https://deb.nodesource.com/setup_20.x | bash - &&\
      - apt-get install -y nodejs

  pre_build:
    commands:
      - echo installing dependencies...
      - npm install

  build:
    commands:
      - echo building...
      - npm run dev


artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build